---
- name: install uncomplicated firewall
  apt: name=ufw state=present update_cache=yes
  tags: firewall

- name: set uncomplicated firewall policy
  ufw: state=enabled policy=deny
  tags: firewall

- name: open ssh port
  ufw: rule=limit port=ssh proto=tcp state=reloaded
  tags: firewall

- name: open ports on firewall
  ufw: rule=allow port={{ item }} proto=tcp state=reloaded
  with_items: "{{ firewall_open_ports }}"
  tags: firewall

- name: install fail2ban
  apt: name=fail2ban state=present update_cache=yes
  tags: firewall, fail2ban

- name: configure fail2ban
  template: src=jail.local dest=/etc/fail2ban/jail.local owner=root group=root
  tags: firewall, fail2ban
  notify:
    - restart fail2ban
